import uuid
from abc import ABC, abstractmethod
from typing import Optional

from kb_biz.models.user import User


class UserRepository(ABC):
    @abstractmethod
    async def get_by_id(self, id: uuid.UUID) -> Optional[User]: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> Optional[User]: ...
    @abstractmethod
    async def list_by_department(self, dept_id: uuid.UUID) -> list[User]: ...
    @abstractmethod
    async def list_by_tenant(self, tenant_id: uuid.UUID) -> list[User]: ...
    @abstractmethod
    async def create(self, user: User) -> User: ...
    @abstractmethod
    async def update(self, user: User) -> User: ...
    @abstractmethod
    async def delete(self, id: uuid.UUID) -> None: ...
